### ISSUE TITLE
Command for blinds (shutters) does not work under Domoticz

### ISSUE THREAD

**Issue by NRJMons** [tnys/nikohomecontrol-domoticz#1]
Hi tnys,

First of all, thanks for the amazing work, I had been struggling with phpMQTT and all and what you did is soooo easier.
So, it works fine for all lights but it doesn't work with shutters control.

My shutters are recognized as lights/switches in Domoticz, I changed it to "blinds" (and tried all options, inverted or not, percentage or not), nothing works.

I wonder if the code you have developed takes the specificity of electric shutters specifically, I'm looking at the code.
Any tips you'd have would be much appreciated. I'm better in PHP than in python but I can find my way.

Thx a bunch in advance.

Cheers
NRJ

**Comment by tnys** [comment]
Hi, 

Thanks for the feedback.  I've just installed my first shutter, so I will look into this the next days.  The code currently only handles lights/switches - I have to implement something specific for shutters.

Cheers
Tom.

**Comment by NRJMons** [comment]
Hi Tom

Great, well, if you need any assistance, tell me, I'm also a developer and I have electric shutters controlled by NHC.
Thanks for all the efforts, the switches/lights work great, really

**Comment by tnys** [comment]
Just added basic support for shutters.

**Comment by NRJMons** [comment]
Hey Tom

Excellent news, thanks a lot, I’ll have a look

Nico

Nicolas Bouillon
Gérant
Katalyst SPRL

www.katalyst.be <http://www.katalyst.be/>

Webshop: www.kavis.be <http://www.kavis.be/>





On 26 Feb 2021, at 16:19, Tom Nys <notifications@github.com> wrote:


Just added basic support for shutters.
